import { Alert, AnalysisResult, CameraFeed, FieldTask, Playbook, TeamMember } from './types';

export const CAMERAS: CameraFeed[] = [
  {
    id: 'cam-01',
    name: 'Pasto Norte (Cocho)',
    location: 'Setor A',
    status: 'active',
    thumbnailUrl: 'https://picsum.photos/seed/cows1/900/600',
  },
  {
    id: 'cam-02',
    name: 'Bebedouro Principal',
    location: 'Setor B',
    status: 'active',
    thumbnailUrl: 'https://picsum.photos/seed/cows2/900/600',
  },
  {
    id: 'cam-03',
    name: 'Curral de Manejo',
    location: 'Sede',
    status: 'active',
    thumbnailUrl: 'https://picsum.photos/seed/cows3/900/600',
  },
  {
    id: 'cam-04',
    name: 'Área de Descanso',
    location: 'Setor C',
    status: 'active',
    thumbnailUrl: 'https://picsum.photos/seed/cows4/900/600',
  },
];

export const INITIAL_HISTORY: AnalysisResult[] = [
  {
    cameraId: 'cam-01',
    timestamp: new Date(Date.now() - 1000 * 60 * 40).toISOString(),
    cattleCount: 15,
    healthScore: 94,
    identifiedIssues: [],
    recommendations: ['Manter rotina e hidratação monitorada.'],
    rawAnalysis: 'Rebanho em comportamento normal de pastejo. Sem sinais visuais de estresse.',
  },
  {
    cameraId: 'cam-01',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 4).toISOString(),
    cattleCount: 14,
    healthScore: 88,
    identifiedIssues: [
      {
        issue: 'Leve agitação',
        description: 'Um animal apresenta movimentação de cabeça repetitiva e deslocamento frequente sem pastejo.',
        possibleCauses: ['Estresse térmico leve', 'Presença de insetos', 'Início de desconforto físico'],
      },
    ],
    recommendations: ['Monitorar animal isolado e revisar sombra no setor.'],
    rawAnalysis: 'A maioria do gado está calma, mas um animal apresenta movimentação excessiva.',
  },
  {
    cameraId: 'cam-01',
    timestamp: new Date(Date.now() - 1000 * 60 * 60 * 26).toISOString(),
    cattleCount: 12,
    healthScore: 55,
    identifiedIssues: [
      {
        issue: 'Animal caído',
        description: 'Bovino detectado em decúbito lateral por período prolongado, sem movimentos de ruminação visíveis.',
        possibleCauses: ['Lesão locomotora', 'Doença metabólica', 'Exaustão severa'],
      },
      {
        issue: 'Possível lesão',
        description: 'Posicionamento anormal do membro posterior direito enquanto deitado.',
        possibleCauses: ['Trauma', 'Fratura', 'Inflamação articular'],
      },
    ],
    recommendations: ['Verificação veterinária imediata.'],
    rawAnalysis: 'Alerta crítico: Animal detectado deitado por longo período sem movimento.',
  },
  {
    cameraId: 'cam-02',
    timestamp: new Date(Date.now() - 1000 * 60 * 35).toISOString(),
    cattleCount: 8,
    healthScore: 91,
    identifiedIssues: [],
    recommendations: ['Manter rotina de limpeza do bebedouro.'],
    rawAnalysis: 'Animais bebendo água regularmente e sem sinais de stress térmico.',
  },
];

export const INITIAL_ALERTS: Alert[] = [
  {
    id: 'alert-01',
    cameraId: 'cam-01',
    severity: 'critical',
    title: 'Animal caído detectado',
    description: 'Bovino ID #452 em decúbito lateral por mais de 3 horas sem movimentação de ruminação.',
    timestamp: '10 minutos atrás',
    location: 'Pasto Norte (Cocho)',
    status: 'active',
  },
  {
    id: 'alert-02',
    cameraId: 'cam-04',
    severity: 'warning',
    title: 'Comportamento agitado',
    description: 'Grupo de 5 animais apresentando correria atípica, possível presença de predador ou estresse por insetos.',
    timestamp: '45 minutos atrás',
    location: 'Área de Descanso',
    status: 'active',
  },
  {
    id: 'alert-03',
    cameraId: 'cam-02',
    severity: 'warning',
    title: 'Nível de água baixo',
    description: 'O bebedouro principal está com nível abaixo de 20%.',
    timestamp: '2 horas atrás',
    location: 'Bebedouro Principal',
    status: 'active',
  },
  {
    id: 'alert-04',
    cameraId: 'cam-03',
    severity: 'info',
    title: 'Movimentação noturna',
    description: 'Atividade normal registrada durante a madrugada.',
    timestamp: '6 horas atrás',
    location: 'Curral de Manejo',
    status: 'resolved',
  },
  {
    id: 'alert-05',
    cameraId: 'cam-01',
    severity: 'warning',
    title: 'Dispersão do lote',
    description: 'Lote com baixa coesão espacial durante o pastejo.',
    timestamp: 'Hoje, 06:20',
    location: 'Pasto Norte',
    status: 'active',
  },
  {
    id: 'alert-06',
    cameraId: 'cam-02',
    severity: 'info',
    title: 'Consumo de água normalizado',
    description: 'Padrão de consumo voltou ao nível esperado após limpeza do bebedouro.',
    timestamp: 'Ontem, 19:10',
    location: 'Bebedouro Principal',
    status: 'resolved',
  },
];

export const INITIAL_TASKS: FieldTask[] = [
  {
    id: 'task-01',
    title: 'Verificar animal em decúbito lateral',
    owner: 'Mariana Rocha',
    priority: 'high',
    status: 'in_progress',
    dueAt: new Date(Date.now() + 1000 * 60 * 45).toISOString(),
    location: 'Pasto Norte',
    notes: 'Levar kit de primeiros socorros e avaliar locomoção.',
    sourceAlertId: 'alert-01',
  },
  {
    id: 'task-02',
    title: 'Reforçar controle de insetos',
    owner: 'Equipe Sanidade',
    priority: 'medium',
    status: 'backlog',
    dueAt: new Date(Date.now() + 1000 * 60 * 60 * 4).toISOString(),
    location: 'Área de Descanso',
    notes: 'Aplicar solução recomendada no perímetro do curral.',
    sourceAlertId: 'alert-02',
  },
  {
    id: 'task-03',
    title: 'Revisar nível do bebedouro',
    owner: 'Henrique Lima',
    priority: 'medium',
    status: 'done',
    dueAt: new Date(Date.now() - 1000 * 60 * 60 * 2).toISOString(),
    location: 'Setor B',
    notes: 'Bomba revisada e fluxo normalizado.',
    sourceAlertId: 'alert-03',
  },
  {
    id: 'task-04',
    title: 'Auditar coesão de lote no pastejo',
    owner: 'Luisa Cardoso',
    priority: 'low',
    status: 'backlog',
    dueAt: new Date(Date.now() + 1000 * 60 * 60 * 10).toISOString(),
    location: 'Pasto Norte',
    notes: 'Confirmar rota de movimentação e revisar saleiros.',
    sourceAlertId: 'alert-05',
  },
];

export const PLAYBOOKS: Playbook[] = [
  {
    id: 'playbook-01',
    title: 'Resposta rápida para animal caído',
    trigger: 'Detecção de decúbito lateral > 2h',
    steps: [
      'Acionar veterinário de plantão e equipe de contenção.',
      'Avaliar sinais vitais e hidratação imediatamente.',
      'Isolar área e monitorar temperatura corporal por 30 minutos.',
    ],
    severity: 'critical',
    slaHours: 1,
    ownerRole: 'Veterinária',
  },
  {
    id: 'playbook-02',
    title: 'Controle de estresse térmico',
    trigger: 'Temperatura > 30°C e queda na movimentação',
    steps: [
      'Redirecionar lote para área de sombra.',
      'Reforçar oferta de água com verificação de fluxo.',
      'Monitorar sinais respiratórios por 2 horas.',
    ],
    severity: 'warning',
    slaHours: 3,
    ownerRole: 'Gestão de Campo',
  },
  {
    id: 'playbook-03',
    title: 'Ajuste de dieta em baixa condição corporal',
    trigger: 'BCS < 2.5 em mais de 5% do lote',
    steps: [
      'Revisar oferta de proteína e energia no cocho.',
      'Separar lote para suplementação direcionada.',
      'Reavaliar BCS após 7 dias.',
    ],
    severity: 'warning',
    slaHours: 12,
    ownerRole: 'Nutrição',
  },
  {
    id: 'playbook-04',
    title: 'Alerta de movimento atípico noturno',
    trigger: 'Atividade noturna acima do padrão',
    steps: [
      'Revisar perímetro e iluminação das cercas.',
      'Checar presença de predadores e ruídos externos.',
      'Ajustar monitoramento com sensores de som.',
    ],
    severity: 'info',
    slaHours: 24,
    ownerRole: 'Segurança',
  },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: 'team-01',
    name: 'Mariana Rocha',
    role: 'Veterinária',
    shift: 'Plantão manhã',
    status: 'field',
    focus: 'Pasto Norte',
  },
  {
    id: 'team-02',
    name: 'Henrique Lima',
    role: 'Operações',
    shift: 'Plantão manhã',
    status: 'available',
    focus: 'Hidratação e cercas',
  },
  {
    id: 'team-03',
    name: 'Luisa Cardoso',
    role: 'Zootecnia',
    shift: 'Plantão tarde',
    status: 'available',
    focus: 'Nutrição e suplementação',
  },
  {
    id: 'team-04',
    name: 'Equipe Sanidade',
    role: 'Sanidade',
    shift: 'Plantão tarde',
    status: 'field',
    focus: 'Controle de insetos',
  },
  {
    id: 'team-05',
    name: 'Lucas Andrade',
    role: 'Segurança',
    shift: 'Plantão noite',
    status: 'offline',
    focus: 'Perímetro externo',
  },
];
